spring:
  datasource:
    url: jdbc:mysql://ted-network/ted
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: P@ssw0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

ted:
  initial-db-file-csv: /data.csv
