version: "3"
services:
  ted-jdbc:
    image: ted-api
    ports:
      - "9999:8080"
    networks:
      - ted-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - ted-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ted_talks

networks:
  ted-mysql: